#ifndef ARISE_SLAM_MID360_CERES_COMPAT_H
#define ARISE_SLAM_MID360_CERES_COMPAT_H

#include <ceres/ceres.h>

#if defined(CERES_VERSION_MAJOR) && \
    (CERES_VERSION_MAJOR > 2 || \
     (CERES_VERSION_MAJOR == 2 && CERES_VERSION_MINOR >= 1))
#define ARISE_SLAM_HAS_CERES_MANIFOLD 1
#else
#define ARISE_SLAM_HAS_CERES_MANIFOLD 0
#endif

#endif  // ARISE_SLAM_MID360_CERES_COMPAT_H
